
import React, { useState, useCallback, useRef, useEffect } from 'react';
import { Header } from './components/Header';
import { Generator } from './components/Generator';
import { Toast } from './components/ui/Toast';
import { generateImage, generateTitle } from './services/geminiService';
import type { Settings, GenerationState, ToastInfo, GeneratedImage } from './types';

const CREDIT_COST_PER_IMAGE = 5;
const INITIAL_CREDITS = 500;

function App() {
  const [generatedImages, setGeneratedImages] = useState<GeneratedImage[]>([]);
  const [credits, setCredits] = useState<number | null>(null);

  const [prompt, setPrompt] = useState<string>('');
  const [settings, setSettings] = useState<Settings>({
    style: 'Cinematic',
    aspectRatio: '9:16',
    creativity: 75,
    negativePrompt: '',
    numImages: 1,
    quality: 'HD',
  });
  
  const [generationState, setGenerationState] = useState<GenerationState>('IDLE');
  const [toast, setToast] = useState<ToastInfo | null>(null);
  
  const imageSpawnCounter = useRef(0);

  useEffect(() => {
    try {
      const savedCredits = localStorage.getItem('kreta-credits');
      if (savedCredits === null) {
        setCredits(INITIAL_CREDITS);
      } else {
        setCredits(JSON.parse(savedCredits));
      }
    } catch (error) {
      console.error("Failed to load credits from localStorage", error);
      setCredits(INITIAL_CREDITS);
    }
  }, []);

  useEffect(() => {
    if (credits !== null) {
      try {
        localStorage.setItem('kreta-credits', JSON.stringify(credits));
      } catch (error) {
        console.error("Failed to save credits to localStorage", error);
      }
    }
  }, [credits]);

  const showToast = (message: string, type: 'success' | 'error') => {
    setToast({ message, type });
    setTimeout(() => setToast(null), 5000);
  };
  
  const handleClearCanvas = () => {
    setGeneratedImages([]);
    imageSpawnCounter.current = 0;
    showToast('Canvas cleared.', 'success');
  }

  const handleGenerate = useCallback(async (promptOverride?: string) => {
    const activePrompt = promptOverride || prompt;
    if (!activePrompt.trim()) {
      showToast('Please enter a prompt to generate an image.', 'error');
      return;
    }

    const cost = settings.numImages * CREDIT_COST_PER_IMAGE;
    if (credits === null || credits < cost) {
        showToast(`Not enough credits. Needs ${cost}, have ${credits ?? 0}.`, 'error');
        return;
    }

    setGenerationState('GENERATING');
    setCredits(prev => (prev !== null ? prev - cost : null));

    const currentCounter = imageSpawnCounter.current;
    const placeholders: GeneratedImage[] = Array.from({ length: settings.numImages }).map((_, index) => {
      const spawnOffset = (currentCounter + index) * 20;
      return {
        id: crypto.randomUUID(),
        src: '',
        title: 'Generating...',
        prompt: activePrompt,
        aspectRatio: settings.aspectRatio,
        x: 100 + spawnOffset,
        y: 100 + spawnOffset,
        status: 'loading' as const,
      };
    });
    
    imageSpawnCounter.current += settings.numImages;

    setGeneratedImages(prev => [...prev, ...placeholders]);

    try {
      const images = await generateImage(activePrompt, settings.aspectRatio, settings.numImages);
      
      let title = "Generated Image";
      if (images.length > 0) {
        title = await generateTitle(activePrompt);
      }
      
      setGeneratedImages(prevImages => {
        const newImages = [...prevImages];
        placeholders.forEach((placeholder, index) => {
          const imageIndex = newImages.findIndex(img => img.id === placeholder.id);
          if (imageIndex !== -1 && images[index]) {
            newImages[imageIndex] = {
              ...newImages[imageIndex],
              src: `data:image/png;base64,${images[index]}`,
              title: title,
              status: 'complete' as const,
            };
          }
        });
        return newImages;
      });

      setGenerationState('COMPLETE');
      showToast(`Images generated successfully! ${cost} credits used.`, 'success');
    } catch (error) {
      console.error('Image generation failed:', error);
      // Refund credits on failure
      setCredits(prev => (prev !== null ? prev + cost : null));
      
      const placeholderIds = placeholders.map(p => p.id);
      setGeneratedImages(prev => prev.filter(img => !placeholderIds.includes(img.id)));
      setGenerationState('ERROR');
      
      const errorMessage = error instanceof Error ? error.message : String(error);
      
      let displayMessage = 'Failed to generate image. Your credits have been refunded.';

      if (errorMessage.includes('SAFETY')) {
        displayMessage = 'Prompt blocked due to safety settings. Credits refunded.';
      } else if (errorMessage.includes('No image generated by the API')) {
        displayMessage = 'The API returned no images. Credits refunded.';
      }
      
      showToast(displayMessage, 'error');
    }
  }, [prompt, settings, credits]);

  return (
    <div className="h-screen w-screen flex flex-col overflow-hidden">
      <Header onClearCanvas={handleClearCanvas} />
      <div className="flex flex-1 overflow-hidden">
        <main className="flex-1 overflow-auto">
          <Generator
            prompt={prompt}
            setPrompt={setPrompt}
            settings={settings}
            setSettings={setSettings}
            generationState={generationState}
            handleGenerate={handleGenerate}
            generatedImages={generatedImages}
            setGeneratedImages={setGeneratedImages}
            credits={credits}
          />
        </main>
      </div>
      {toast && (
        <Toast
          message={toast.message}
          type={toast.type}
          onClose={() => setToast(null)}
        />
      )}
    </div>
  );
}

export default App;
