
import { GoogleGenAI } from "@google/genai";
import type { Settings } from '../types';

// Helper to get the AI client instance
const getAiClient = (apiKey: string) => {
  return new GoogleGenAI({ apiKey });
};

// Helper for delay
const wait = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

export const generateImage = async (prompt: string, aspectRatio: Settings['aspectRatio'], numImages: number, apiKey: string): Promise<string[]> => {
    if (!apiKey) throw new Error("API Key is required");
    
    const ai = getAiClient(apiKey);
    const generatedImages: string[] = [];
    
    // Max retries for rate limiting
    const MAX_RETRIES = 3;
    
    try {
        // We use sequential processing with delays to handle Free Tier strict rate limits.
        for (let i = 0; i < numImages; i++) {
            
            // If asking for multiple images, add a safety pause between them to avoid burst limits
            if (i > 0) {
                await wait(3000); 
            }

            let attempts = 0;
            let success = false;

            while (attempts < MAX_RETRIES && !success) {
                try {
                    const response = await ai.models.generateContent({
                        model: 'gemini-2.5-flash-image',
                        contents: prompt,
                        config: {
                            imageConfig: {
                                aspectRatio: aspectRatio,
                            }
                        },
                    });

                    // Extract base64 data
                    let foundImage = false;
                    for (const part of response.candidates?.[0]?.content?.parts || []) {
                        if (part.inlineData) {
                            generatedImages.push(part.inlineData.data);
                            foundImage = true;
                            success = true; // Mark as successful to exit retry loop
                            break;
                        }
                    }

                    if (!foundImage) {
                        console.warn(`Request ${i+1}: No image data found.`);
                        // If no image but no error, we don't retry, just move on or throw specific error
                        throw new Error("No image generated by model.");
                    }

                } catch (innerError: any) {
                    attempts++;
                    
                    const isRateLimit = innerError.message && (
                        innerError.message.includes('429') || 
                        innerError.message.includes('Quota') ||
                        innerError.message.includes('RESOURCE_EXHAUSTED')
                    );

                    if (isRateLimit && attempts < MAX_RETRIES) {
                        const delayTime = 2000 * attempts; // Wait 2s, then 4s, etc.
                        console.log(`Rate limit hit. Retrying in ${delayTime}ms... (Attempt ${attempts}/${MAX_RETRIES})`);
                        await wait(delayTime);
                    } else if (isRateLimit && attempts >= MAX_RETRIES) {
                        console.error(`Failed after ${MAX_RETRIES} attempts due to rate limiting.`);
                        throw innerError; // Throw to main catch block
                    } else {
                        // If it's not a rate limit error (e.g., Safety), fail immediately
                        console.warn(`Failed to generate image ${i + 1} due to non-rate-limit error:`, innerError);
                        throw innerError;
                    }
                }
            }
        }

        if (generatedImages.length > 0) {
            return generatedImages;
        } else {
            throw new Error("No images were generated. The API might be blocking the prompt or experiencing high traffic.");
        }
    } catch (error: any) {
        console.error("Gemini API Error:", error);
        throw new Error(error.message || String(error));
    }
};

export const generateTitle = async (prompt: string, apiKey: string): Promise<string> => {
    if (!apiKey) return "Untitled Artwork";
    
    try {
        const ai = getAiClient(apiKey);
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: `Create a single, concise, and artistic title (maximum 4 words) for an image generated from the following prompt. Do not provide suggestions, alternatives, or quotation marks. Just the title. Prompt: "${prompt}"`,
        });
        return response.text?.trim().replace(/"/g, '') || "Untitled Artwork";
    } catch (error) {
        console.error("Title generation failed:", error);
        return "Untitled Artwork";
    }
};
