
import { GoogleGenAI } from "@google/genai";
import type { Settings } from '../types';

// Helper to get the AI client instance
const getAiClient = (apiKey: string) => {
  return new GoogleGenAI({ apiKey });
};

export const generateImage = async (prompt: string, aspectRatio: Settings['aspectRatio'], numImages: number, apiKey: string): Promise<string[]> => {
    if (!apiKey) throw new Error("API Key is required");
    
    const ai = getAiClient(apiKey);
    
    const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: prompt,
        config: {
          numberOfImages: numImages,
          outputMimeType: 'image/png',
          aspectRatio: aspectRatio,
        },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
        return response.generatedImages.map(img => img.image.imageBytes);
    } else {
        throw new Error("No image generated by the API.");
    }
};

export const generateTitle = async (prompt: string, apiKey: string): Promise<string> => {
    if (!apiKey) return "Untitled Artwork";
    
    try {
        const ai = getAiClient(apiKey);
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: `Create a single, concise, and artistic title (maximum 4 words) for an image generated from the following prompt. Do not provide suggestions, alternatives, or quotation marks. Just the title. Prompt: "${prompt}"`,
        });
        return response.text.trim().replace(/"/g, '');
    } catch (error) {
        console.error("Title generation failed:", error);
        return "Untitled Artwork";
    }
};
